### ISSUE TITLE
 Can only install one of: monolog/monolog[2.0.0, 1.25.4]

### ISSUE THREAD

**Issue by wonli** [stackerzzq/phpnsq#11]
- okstuff/phpnsq 3.1 requires monolog/monolog ^2.0 -> satisfiable by monolog/monolog[2.0.0, 2.0.1, 2.0.2, 2.1.0].
- Can only install one of: monolog/monolog[2.0.0, 1.25.4].
- Can only install one of: monolog/monolog[2.0.1, 1.25.4].
- Can only install one of: monolog/monolog[2.0.2, 1.25.4].
- Can only install one of: monolog/monolog[2.1.0, 1.25.4].
- Installation request for monolog/monolog (locked at 1.25.4) -> satisfiable by monolog/monolog[1.25.4].

**Comment by cgxxv** [comment]
@wonli Please try the latest master branch.
