### ISSUE TITLE
stream_select failed,  fclose() supplied resource is not a valid stream source in Tunnel.php

### ISSUE THREAD

**Issue by outman** [stackerzzq/phpnsq#12]
When consumer exit with exception, i found pfsockopen produced unexpected behavior when send new message to nsq in consumer context. Change pfsockopen to fsockopen, it works correct. My code depends on old version 1.0.1 (with composer install)，_**can't upgrade new version because php runtime version**_, and can't send pull request to your project based version 1.0.1, can you help me to fix it?

Change fpsockopen to fsockopen in src/phpnsq/Utility/Stream.php on tag 1.0.1 and then tag it 1.0.2 .
![image](https://user-images.githubusercontent.com/532893/131997771-1dd0798c-20ca-4fd7-a264-bc7a027117db.png)

Thank you !

**Comment by cgxxv** [comment]
Sorry for the late reply, please check 1.0.2.

**Comment by outman** [comment]
Thank u, it's working. @wk30
