### ISSUE TITLE
Issue with monolog

### ISSUE THREAD

**Issue by marinsagovac** [stackerzzq/phpnsq#2]
Using symfony 4 there are issues when calling constructor new Nsq() like:

```
use OkStuff\PhpNsq\Message\Message;
use OkStuff\PhpNsq\PhpNsq;
use OkStuff\PhpNsq\Command\Base;

        $this->config = [
            "nsq" => [
                "nsqd-addrs" => [
                    "127.0.0.1:4150",
                ],
                "logdir" => "/tmp",
            ],
        ];

        $this->client = new PhpNsq($this->config);

        var_dump($this->client); exit;
```

It' triggered error even when force to use Logging from vendor PhpNsq:

`php.CRITICAL: Class 'OkStuff\PhpNsq\Utility\Logging' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'OkStuff\\PhpNsq\\Utility\\Logging' not found at /data/projects/...vendor/okstuff/phpnsq/src/phpnsq/PhpNsq.php:25)"} []`

I've tried using alias as 

`use OkStuff\PhpNsq\Utility\Logging;`

and changed a path: 

`    "logdir" => "/tmp",`

that has really full write access. Nothing helps.

On vendor if I comment a code: 

```
    public function __construct($nsq)
    {
        $this->reader = new reader();
        $this->logger = new Logging("PHPNSQ", $nsq["nsq"]["logdir"]);
        $this->pool   = new Pool($nsq);
    }
```

It occured another errors from instance Pool.

**Comment by cgxxv** [comment]
@marinsagovac It seems that your classes are not loaded correctly. Please check.

**Comment by frankfarmer** [comment]
https://github.com/stackerzzq/phpnsq/tree/master/src/phpnsq/Utillity

Looks like that directory is named "Utillity" with two Ls, while the package name has only one L.

That's probably causing autoload problems.
