### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by moniang** [stackerzzq/phpnsq#6]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for okstuff/phpnsq dev-master -> satisfiable by okstuff/phpnsq[dev-master].
    - Conclusion: remove monolog/monolog 2.x-dev
    - Conclusion: don't install monolog/monolog 2.x-dev
    - okstuff/phpnsq dev-master requires monolog/monolog ^1.23|^1.24 -> satisfiable by monolog/monolog[1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.x-dev].
    - Can only install one of: monolog/monolog[1.23.0, 2.x-dev].
    - Can only install one of: monolog/monolog[1.24.0, 2.x-dev].
    - Can only install one of: monolog/monolog[1.25.0, 2.x-dev].
    - Can only install one of: monolog/monolog[1.25.1, 2.x-dev].
    - Can only install one of: monolog/monolog[1.25.2, 2.x-dev].
    - Can only install one of: monolog/monolog[1.25.3, 2.x-dev].
    - Can only install one of: monolog/monolog[1.x-dev, 2.x-dev].
    - Installation request for monolog/monolog (locked at 2.x-dev) -> satisfiable by monolog/monolog[2.x-dev].

**Comment by cgxxv** [comment]
@moniang Please check 2.0 version.
